name: MSBuild

on:
  pull_request:
    branches:
      - "**"
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'image/**'
      - 'docs/**'
      - '**/*.md'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify:
    uses: ./.github/workflows/reusable-build-and-test.yml
    with:
      configuration: Release
      run_tests: true