name: Basic verify

on:
  pull_request:
    branches:
      - "**"
    types:
      - opened
      - synchronize
      - reopened
    paths-ignore:
      - 'image/**'
      - 'docs/**'
      - '**/*.md'
  workflow_dispatch:

jobs:
  compile-check:
    runs-on: windows-2022
    env:
      CONFIGURATION: Release

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: recursive
        lfs: true

    - name: setup-msvc
      uses: egor-tensin/vs-shell@v2
      with:
        # Target architecture
        arch: x86

    - name: Build Program and UT (MSVC)
      run: |
        MSBuild FA2sp.sln /m /p:Configuration="${{ env.CONFIGURATION }}" /p:Platform=x86

    - name: Copy binaries to Supplementary
      shell: pwsh
      run: |
        if (Test-Path "Release/FA2sp.dll") {
            Copy-Item -Force "Release/FA2sp.dll" "Supplementary/FA2sp.dll"
        }
        if (Test-Path "Release/FA2sp.UnitTest.dll") {
            Copy-Item -Force "Release/FA2sp.UnitTest.dll" "Supplementary/FA2sp.UnitTest.dll"
        }

    - name: do UT
      shell: cmd
      run: |
        cd Supplementary
        RunUnitTest.bat

    - name: Upload UT Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: FA2sp-UT-Results-pr-${{ github.run_number }}
        path: |
          Supplementary/UnitTest.log
          Supplementary/UnitTest.xml
          Supplementary/syringe.log
        retention-days: 7

    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: FA2sp-pr-${{ github.run_number }}
        path: |
          Release/FA2sp.dll
          Release/FA2sp.pdb
        retention-days: 7
